#!/bin/bash

# generate-checklist.sh - Generates a comprehensive checklist from system design concepts

set -e

SPEC_DIR=".spec"
CONCEPTS_FILE="$SPEC_DIR/system-design/concepts.md"
OUTPUT_FILE="$SPEC_DIR/system-design/checklist.md"

echo "📋 Generating System Design Concepts Checklist..."

if [ ! -f "$CONCEPTS_FILE" ]; then
    echo "❌ Error: Concepts file not found at $CONCEPTS_FILE"
    exit 1
fi

# Create header
cat > "$OUTPUT_FILE" << 'EOF'
# System Design Concepts Checklist

This checklist tracks the implementation status of all system design concepts across the project phases.

**Last Updated**: $(date +"%Y-%m-%d")

## How to Use

- [ ] = Not yet covered
- [x] = Implemented and tested
- [~] = Partially implemented
- [!] = Skipped (with justification)

Update this checklist as you complete each phase and implement the corresponding concepts.

---

EOF

# Extract all checklist items from concepts.md
echo "Extracting checklist items..."

# Read the concepts file and preserve the structure
while IFS= read -r line; do
    # Check if line is a header (###)
    if [[ $line =~ ^###[[:space:]](.+)$ ]]; then
        echo "" >> "$OUTPUT_FILE"
        echo "$line" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    # Check if line is a checkbox item (with optional space before dash)
    elif [[ $line =~ ^[[:space:]]*-[[:space:]]\[.?\][[:space:]](.+)$ ]]; then
        # Replace [x] or [ ] with [ ] to reset all checkboxes
        item=$(echo "$line" | sed 's/\[.\]/[ ]/')
        echo "$item" >> "$OUTPUT_FILE"
    fi
done < "$CONCEPTS_FILE"

# Add summary section
cat >> "$OUTPUT_FILE" << 'EOF'

---

## Progress Summary

To calculate your progress:

```bash
# Total items
grep -c "^- \[ \]" .spec/system-design/checklist.md

# Completed items
grep -c "^- \[x\]" .spec/system-design/checklist.md

# Partial items
grep -c "^- \[~\]" .spec/system-design/checklist.md
```

## Phase Mapping

Refer to `.spec/phases/README.md` to see which concepts are covered in each phase.

## Notes

Add notes about specific concept implementations:

- **Date**: YYYY-MM-DD
  - **Concept**: Concept name
  - **Phase**: Phase number
  - **Notes**: Implementation details or challenges

---

**Generated by**: `.spec/scripts/generate-checklist.sh`
EOF

echo "✅ Checklist generated at $OUTPUT_FILE"
echo ""
echo "Summary:"
total_items=$(grep -c "^- \[ \]" "$OUTPUT_FILE" || echo "0")
echo "  Total concepts: $total_items"
echo ""
echo "You can now track your progress by updating the checklist as you complete each concept!"
