server:
  host: "localhost"
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 30s

logging:
  level: "info"
  format: "json"
  output: "stdout"

cors:
  allowed_origins:
    - "http://localhost:3000"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
