server:
  host: "localhost"
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 30s

logging:
  level: "info"
  format: "json"
  output: "stdout"

cors:
  allowed_origins:
    - "http://localhost:3000"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Content-Type"
    - "Authorization"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  database: "angidi_dev"
  sslmode: "disable"
  max_conns: 25
  min_conns: 5
  max_conn_lifetime: 1h
  max_conn_idle_time: 15m
